USE [master]
GO

/****** Object:  Database [Arkadium]    Script Date: 15.04.2018 22:16:06 ******/
CREATE DATABASE [Arkadium]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Arkadium', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Arkadium.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Arkadium_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Arkadium_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Arkadium] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Arkadium].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Arkadium] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Arkadium] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Arkadium] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Arkadium] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Arkadium] SET ARITHABORT OFF 
GO

ALTER DATABASE [Arkadium] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Arkadium] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Arkadium] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Arkadium] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Arkadium] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Arkadium] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Arkadium] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Arkadium] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Arkadium] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Arkadium] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Arkadium] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Arkadium] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Arkadium] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Arkadium] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Arkadium] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Arkadium] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Arkadium] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Arkadium] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Arkadium] SET  MULTI_USER 
GO

ALTER DATABASE [Arkadium] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Arkadium] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Arkadium] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Arkadium] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Arkadium] SET  READ_WRITE 
GO


